### ISSUE TITLE
AttributeError at /academic-procedures/main/ 'NoneType' object has no attribute 'designation'

### ISSUE THREAD

**Issue by Anunaya07** [FusionIIIT/Fusion#1006]
**Describe the bug**
access academic-procedure page for some faculty results in attribute error.

**To Reproduce**

1. login in with email: atul@iiitdmj.ac.in
2. Click on on academic modules
3. See error

**Expected behavior**
Academic module page should open with relevant attributes. 

**Screenshots**
error:

![AttributeError at _academic-procedures_main_ - Brave 24_01_2023 4_32_32 AM](https://user-images.githubusercontent.com/76819712/214227453-82d42587-0ca3-4a98-8253-3520d09f0b56.png)

expected behaviour:
![Fusion! - Brave 23_01_2023 4_58_49 PM](https://user-images.githubusercontent.com/76819712/214227499-ec07ee44-7075-4121-b9f6-abec484cc6f0.png)

**Comment by Anunaya07** [comment]
Issue is resolved:

The problem was in email address table (accounts) where **atul@iiitdmj,ac.in was associated with a different username which was not present in holds designation table.**
![Select email address to change _ Django site admin - Brave 24_01_2023 11_28_03 AM](https://user-images.githubusercontent.com/76819712/214309551-e620fbdb-2a7c-4c99-b75c-1514e09434f9.png)

how to resolve?
**change the username in email address table(accounts) to AG**
 
![Select email address to change _ Django site admin - Brave 24_01_2023 11_29_18 AM](https://user-images.githubusercontent.com/76819712/214309693-5bd50c8f-ea03-468a-a193-689c3dbbb022.png)

**Comment by akshatnema** [comment]
@Anunaya07 Have you made any PR in order to resolve this issue?

**Comment by PranshuNayak** [comment]
@Anunaya07 to resolve the issue please check the associated view function with this url . This error shows that you are trying to access attributes of a null object , so after quering the object from the database check whether the returned object is NULL or not.
You can find a detailed explanation in this post [https://stackoverflow.com/questions/37912297/django-attributeerror-nonetype-object-has-no-attribute-first-name](url)

**Comment by PranshuNayak** [comment]
The issue is resolved on 214
