### ISSUE TITLE
Designations not present in database

### ISSUE THREAD

**Issue by rush1kesh-010** [FusionIIIT/Fusion#1457]
The department admins that are displayed in the google sheet attached in the mail are not present in the database designations, and the usernames of the designations have different designations than the ones expected as per the sheet.
Please provide designations in the database as well; as staff view is dependent on the user designation of the admins and their usernames.

**Comment by prabhatsuman** [comment]
@rush1kesh-010 can you please specify which department admins are not working on the deployed database.

**Comment by rush1kesh-010** [comment]
Designation      |   |   | Username
deptadmin_cse |   |   | garewald
deptadmin_ece |   |   | ayesha
deptadmin_me |   |   | bharti
deptadmin_sm |   |   | krajesh

The designations of these usernames do not exist as shown above in the google sheet, and hence access to staff view as per designation for the specified branch cannot be given.
