### ISSUE TITLE
Group 21 Counselling Cell module UI Design and Database Schema

### ISSUE THREAD

**Issue by tarang75490** [FusionIIIT/Fusion#321]
[Counselling cell.pdf](https://github.com/FusionIIIT/Fusion/files/6141538/Counselling.cell.pdf)

**Comment by garg3133** [comment]
@tarang75490 Instead of attaching a PDF file, can you edit the issue and add your UI designs in the issue itself, like I said on the mail. 

Also, please open a separate issue for the database schema.

**Comment by garg3133** [comment]
For the UI part, there should be an option to see the details of the Head counsellor, Student coordinator, that person's student guide and faculty counsellor.

Also, there should be an option for students to request a meeting with the student guide or faculty counsellor.

**Comment by tarang75490** [comment]
> n option for students to reque



> For the UI part, there should be an option to see the details of the Head counsellor, Student coordinator, that person's student guide and faculty counsellor.
> 
> Also, there should be an option for students to request a meeting with the student guide or faculty counsellor.

We will consider it and try to implement it.
