### ISSUE TITLE
Group 12 AC-1 UI Design

### ISSUE THREAD

**Issue by zjilani** [FusionIIIT/Fusion#323]
[AC1.pdf](https://github.com/FusionIIIT/Fusion/files/6141730/AC1.pdf)

**Comment by garg3133** [comment]
@zjilani Can you please place the screenshots in the issue itself instead of attaching a PDF file. It's hard to access the PDF file, as we need to download it first.

**Comment by zjilani** [comment]
![1](https://user-images.githubusercontent.com/54178159/111970661-81a22180-8b21-11eb-83bd-5a1b6ff925cf.jpeg)
![2](https://user-images.githubusercontent.com/54178159/111970672-85ce3f00-8b21-11eb-8aa8-f97b12f185bc.jpeg)
![3](https://user-images.githubusercontent.com/54178159/111970680-89fa5c80-8b21-11eb-8a86-607856f64016.jpeg)
![4](https://user-images.githubusercontent.com/54178159/111970691-8cf54d00-8b21-11eb-86c4-fef2a9f8f69e.jpeg)
![5](https://user-images.githubusercontent.com/54178159/111970709-9088d400-8b21-11eb-9f25-87bef9c4d5aa.jpeg)
![6](https://user-images.githubusercontent.com/54178159/111970720-941c5b00-8b21-11eb-9ad8-418abb4d6929.jpeg)
![7](https://user-images.githubusercontent.com/54178159/111970729-97174b80-8b21-11eb-97fe-ed9250fbe1d9.jpeg)
