### ISSUE TITLE
Group #20, HA-1 Hostel Management Module, UI Design

### ISSUE THREAD

**Issue by hemant9898** [FusionIIIT/Fusion#327]
We have made UI for some use-case, and we are working on other use cases, please find the attachment. 
[HostelManagementModuleUI.pdf](https://github.com/FusionIIIT/Fusion/files/6141895/HostelManagementModuleUI.pdf)

**Comment by garg3133** [comment]
@hemant9898 Instead of attaching the pdf file, can you please put the screenshots in the issue description itself?

**Comment by hemant9898** [comment]
![All](https://user-images.githubusercontent.com/56092046/111167058-badd0d80-85c6-11eb-8e54-a1d39a6586e5.png)
![CaretakeWarden](https://user-images.githubusercontent.com/56092046/111167071-be709480-85c6-11eb-9f19-e51348927f9d.png)
![Notice](https://user-images.githubusercontent.com/56092046/111167101-c4ff0c00-85c6-11eb-9337-b71228508382.jpg)
![GuestBookDetail](https://user-images.githubusercontent.com/56092046/111167120-c9c3c000-85c6-11eb-9acf-2a52a1abc40f.jpg)
![StaffCaretakerShift](https://user-images.githubusercontent.com/56092046/111167153-d0523780-85c6-11eb-9465-a260e55bdeca.jpg)
![UserAttendence](https://user-images.githubusercontent.com/56092046/111167172-d47e5500-85c6-11eb-81fd-fce7f5049a62.jpg)
![BookGuestRoom](https://user-images.githubusercontent.com/56092046/111167185-d8aa7280-85c6-11eb-8985-095524e83cbe.jpg)
