### ISSUE TITLE
Group #17 Programme & Curriculum Module Database Schema

### ISSUE THREAD

**Issue by bibinbobk** [FusionIIIT/Fusion#338]
For our Programme & Curriculum module, we designed the following database schema.
Every `COURSE` belongs to a particular `SEMESTER` _(or different semesters of other programmes),_ and every `SEMESTER` belongs to a particular `CURRICULUM`, and a `CURRICULUM` to a particular `PROGRAMME`. It is also required _(by Dr.Atul Gupta)_ that Acadmic_Incharge should always able to see a history of past `COURSES` / `SEMESTERS` / `CURRICULUMS` / `PROGRAMMES` offered by the Institute. 
Keeping these in mind, we designed this👇.
![FusionIIIT - PCM - Database Schema](https://user-images.githubusercontent.com/57832856/111429006-59c84d80-871e-11eb-87ee-0f99a2f6e7cb.png)

**Comment by starboy007-debug** [comment]
- [ ]   programme_curriculum/curriculums/2/

        issue : Search box at unnecessary modules with no change in view  & obsolete curriculum is not updated(blank)

- [x]   programme_curriculum/curriculum_semesters/9/

        issue : phd curriculum is empty otherwise this sub link could be eliminated from the module(if phd has no curriculum)

- [ ]  programme_curriculum/batches/ 
        issue : Finished batches are not visible

**Comment by starboy007-debug** [comment]
@tushhr
