### ISSUE TITLE
Central Mess Module

### ISSUE THREAD

**Issue by abhishek-geek** [FusionIIIT/Fusion#489]
## All the issues related to the Central Mess module

> Please number the issues properly so that we can refer them while discussing to resolve the issues.

- [ ] 1. Cannot open "/mess".
![Screenshot from 2021-09-13 10-48-02](https://user-images.githubusercontent.com/54780847/133027968-e2948676-893d-4053-bc1a-6003e123698d.png)

**Comment by abhishek-geek** [comment]
@akanimesh please give some insights on how to resolve the first task.

**Comment by akanimesh** [comment]
@abhishek-geek can you post full screenshot of the error specifically of that traceback part.

**Comment by abhishek-geek** [comment]
> @abhishek-geek can you post full screenshot of the error specifically of that traceback part.

![full-img](https://user-images.githubusercontent.com/54780847/133092491-064ceed3-b391-49f3-bb05-469406b9345c.jpeg)

**Comment by garg3133** [comment]
@abhishek-geek Actually, there's some dependency problem in the Central Mess module. You need to first create an instance for the user in the `MessInfo` table and then only you'll be able to access the Central Mess module for that user.

You can create a new instance in the `MessInfo` table using the Admin Portal of the website.

**Comment by garg3133** [comment]
I think the solution here would be to first check if there's an instance already present for that user in the `MessInfo` table, and if the instance is not present, ask the user to first fill in the details for the `MessInfo` through UI (which can be done by redirecting the user to a separate page, and once the user submits the details, the user can be redirected back to the Central Mess module).

**Comment by abhishek-geek** [comment]
Thanks @garg3133 sir, I will try to fix all this.
