### ISSUE TITLE
Gymkhana Module

### ISSUE THREAD

**Issue by santhoshcharan-001** [FusionIIIT/Fusion#490]
<img width="960" alt="issue-2" src="https://user-images.githubusercontent.com/71368415/133550906-510765d8-5e22-4fc7-9f9e-991318153d43.PNG">
<img width="960" alt="issue-1" src="https://user-images.githubusercontent.com/71368415/133550912-96272855-8b78-4602-81ad-6dac41f54434.PNG">

In the module Gymkhana, the dropdown menu in club sessions and member records weren't getting closed when we click outside the divison as shown in the photos. But whereas in the apply divison, the dropdown menu was perfect and functionality was a bit different.

**Comment by harshit-2300** [comment]
I have confirmed the bug, you can fix the issue and make a pull request.
