### ISSUE TITLE
Gymkhana Module

### ISSUE THREAD

**Issue by santhoshcharan-001** [FusionIIIT/Fusion#491]
There are two more issues in this Gymkhana module. They are:
1) In the divison of member records, when we are interested in serching for records of a particular club with the dropdown menu, we are unable to get the data with single click, as it is taking two clicks to get the data except for the club "Saaz".
2) The second issue is when we click on any club except saaz its blank but once we click on saaz club, we are able to see record of one person, after that if we select any other club, the records of only "Saaz" was appearing as shown in the screenshot.

![issue-4](https://user-images.githubusercontent.com/71368415/133588880-9d9dc386-22e9-4718-8375-445776a70ae5.jpeg)
![issue-3](https://user-images.githubusercontent.com/71368415/133588886-39a91248-bd44-44c2-b882-2eefed288a56.jpeg)

**Comment by harshit-2300** [comment]
I have confirmed the bug, you can fix the issue and make a pull request.
