### ISSUE TITLE
Academic Procedure Module (Issue#1)

### ISSUE THREAD

**Issue by garvitgupta13** [FusionIIIT/Fusion#492]

**Comment by garvitgupta13** [comment]
- [ ]  2.  Cannot open `/academic-procedures/fac/`
![image](https://user-images.githubusercontent.com/70805691/133595750-6f92be9b-c9ea-41b4-aaa3-a63e8bec4c7b.png)

**Comment by garvitgupta13** [comment]
- [ ] 3. Close button overlaps the properties icon on opening any pdf.

![image](https://user-images.githubusercontent.com/70805691/133596482-14b01acd-1149-4a01-a8a4-15cb791fa49a.png)
![image](https://user-images.githubusercontent.com/70805691/133596694-27b65d24-dc20-486f-a97d-f7fdabf11054.png)

**Comment by garvitgupta13** [comment]
- [ ] 4. Unable to change branch `/academic-procedures/stu/`

![image](https://user-images.githubusercontent.com/70805691/133599180-3cdfe5b3-40b8-4bb1-8224-8a12f330fcfe.png)

**Comment by ChiragSharma1** [comment]
- [ ]  5. local variable 'content' referenced before assignment

![image](https://user-images.githubusercontent.com/63919014/133604115-6d8a492d-fd1d-41b6-8d83-65d8514943b1.png)

**Comment by kartik077-cr7** [comment]
- [ ] 4. An error occurred while clicking the course name, of course, if we logged in via any faculty.
 
![Screenshot (161)](https://user-images.githubusercontent.com/64568294/133926490-8f030109-18f9-4f22-8107-2f0305db0e6b.png)

**Comment by arrnavvv** [comment]
- [ ] 5. No exception handling for unregistered urls. 
      `academic-procedures/random-stuff`

![Screenshot (28)](https://user-images.githubusercontent.com/61576354/133927953-c2230525-d5b8-4a66-9802-387b84e51878.png)

**Comment by garvitgupta13** [comment]
- [x]  A user can add the same course multiple times during a semester
`academic-procedures/addCourse/`
![image](https://user-images.githubusercontent.com/70805691/150686015-09bee87c-d7c6-4d08-a7c0-d127a5c343fe.png)

**Comment by tushhr** [comment]
@garvitgupta13 don't link the issue to the PR, instead, you can use hyperlinks because closing one PR will close the whole issue.

**Comment by garvitgupta13** [comment]
> 

No, it won't close
And we are directed to link issue in every PR

**Comment by garvitgupta13** [comment]
> @garvitgupta13 don't link the issue to the PR, instead, you can use hyperlinks because closing one PR will close the whole issue.
No, it won't close issue
And we are directed to link issue in every PR
