### ISSUE TITLE
Complaint Module

### ISSUE THREAD

**Issue by KuldeepSingh037** [FusionIIIT/Fusion#493]
Issues related to the Complaint Module

**Comment by KuldeepSingh037** [comment]
- [x] Can not open the link to reassign the worker.
- [x] No Button for a supervisor to reassign a worker on a Complaint.

**Comment by anurag0singh** [comment]
@KuldeepSingh037 can you also add details like:
1. The address to the particular page.
2.  A screenshot of the page as well.

**Comment by KuldeepSingh037** [comment]
End point : supervisor/caretaker_id_know_more/(?P<caretaker_id>[0-9]+)/complaint_reassign_super/(?P<iid>[ 0-9]+)/$

Can not click and open the above end-point and reassign a worker.


![Screenshot (36)](https://user-images.githubusercontent.com/71912247/151006568-8073b56a-be05-4681-92b8-51a260522c23.png)

**Comment by KuldeepSingh037** [comment]
separate issue created.
