### ISSUE TITLE
Library Module

### ISSUE THREAD

**Issue by ssmharsh** [FusionIIIT/Fusion#495]
- [ ] Issue Date and Return Date are incorrectly sorted

![Screenshot (232)](https://user-images.githubusercontent.com/66547035/134042343-899aa622-5457-4500-baca-b548ca78cc7f.png)

.

- [ ]  author and book search keyword split while showing result

![Screenshot (239)](https://user-images.githubusercontent.com/66547035/134044707-77a3b494-2ccb-47a3-be9d-98f75ee97684.png)

**Comment by harshit-2300** [comment]
@ssmharsh 1) only top 4 are getting sorted I think.  
2) The searched word is splliting the results, can fix it by highlighting it instead of splitting.
