### ISSUE TITLE
Group 19 : OfficeModule_officeOfDeanAcademics

### ISSUE THREAD

**Issue by 29rj** [FusionIIIT/Fusion#496]
![Screenshot from 2021-09-26 21-25-36](https://user-images.githubusercontent.com/70429608/134815087-562fbffa-c03a-4b10-9243-2ebc2e9e03b7.png)

Name of Instructor method is not there in module.py instead it should be Curriculum_Instructor

**Comment by 29rj** [comment]
If student has logged then OfficeOfDeanAcademics page should not be accessible.

**Comment by SrishtiSingh2001** [comment]
Thanks for opening the issue!
The issue is valid.
