### ISSUE TITLE
Group 19 : OfficeModule_directorOffice

### ISSUE THREAD

**Issue by 29rj** [FusionIIIT/Fusion#497]
![Screenshot from 2021-09-26 21-31-39](https://user-images.githubusercontent.com/70429608/134815271-7b2ce98f-1223-40e9-b60d-65c9a49a8c8b.png)

**Comment by 29rj** [comment]
Not able to return any http response due to logical error in the directorOffice function in views.py under officeModule app

**Comment by 29rj** [comment]
If student try login into this page then it should give "Not Authorised To See".

**Comment by SrishtiSingh2001** [comment]
Thanks for opening the issue!
Approved.
