### ISSUE TITLE
Group 19: OfficeModule_OfficeofHOD

### ISSUE THREAD

**Issue by 29rj** [FusionIIIT/Fusion#498]
![Screenshot from 2021-09-26 21-33-52](https://user-images.githubusercontent.com/70429608/134815355-709f61bc-7a5f-4bec-84b6-b47c082612d4.png)

Front-End part: Alignment is not perfect

**Comment by SrishtiSingh2001** [comment]
Issue Approved.
You may raise a PR.

**Comment by SrishtiSingh2001** [comment]
Approved!
