### ISSUE TITLE
Group#6  Research Procedures Module

### ISSUE THREAD

**Issue by Nagaraju6242** [FusionIIIT/Fusion#501]
Students can add and modify patents filed by faculty, it's just hidden in the UI.
Backend verification is not done.

![fusion](https://user-images.githubusercontent.com/62198428/149183439-b46bc7b7-db14-47d8-bc31-827b0dd5d078.png)

**Comment by subodhsiddharth** [comment]
In patent form attached file is a required field in front end but in database field is not set as required .
File to be selected is pdf but we can select any file.

![form](https://user-images.githubusercontent.com/65944635/149198677-b6918b8d-e099-4ab6-a7f6-d76e67b3cbe0.png)

**Comment by MananJethwani** [comment]
Thanks for opening this issue.
kindly ask kumar aryan to review this issue then you can open a PR.
