### ISSUE TITLE
creating forms in fusion iiit/recruitment

### ISSUE THREAD

**Issue by ranjankumar-collab** [FusionIIIT/Fusion#503]
creating  teaching and non teaching staff form 
![teaching](https://user-images.githubusercontent.com/60751710/150633356-228fd4a0-29b2-46d6-8f2f-ee1f185abfc4.png)
![non teaching](https://user-images.githubusercontent.com/60751710/150633363-cf341034-81ca-43d0-a0f2-8c1e8b5c0ec2.png)

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue.
Please create a PR with a fix for this issue.

**Comment by chiragagrawal026** [comment]
You have not yet opened a PR for this issue.
Please open a pull request resolving this issue.

**Comment by chiragagrawal026** [comment]
Still a PR is not created.

**Comment by ranjankumar-collab** [comment]
give me some time to do change then will do a pull request

**Comment by chiragagrawal026** [comment]
This was this week's task.

**Comment by ranjankumar-collab** [comment]
![Screenshot (1612)](https://user-images.githubusercontent.com/60751710/150748437-8eea685f-645f-4257-90f6-911ec579e127.png)
![Screenshot (1613)](https://user-images.githubusercontent.com/60751710/150748441-290d836f-b7a0-4618-95d7-158f74eb36c8.png)
![Screenshot (1623)](https://user-images.githubusercontent.com/60751710/150748444-4d59c84a-0db0-4779-ae8a-78d5e37606f6.png)
![Screenshot (1634)](https://user-images.githubusercontent.com/60751710/150748445-3c8dbadd-cd6a-48e1-861c-6ad856c8ba79.png)
![Screenshot (1651)](https://user-images.githubusercontent.com/60751710/150748448-54473552-c596-4cb2-8503-bed6e77cfbc3.png)


i am changing the ui to make the form ,will take time for pull request of this issue ,first week assignment completed ,see first issue pull request (iiit/recruitment /admine) one

**Comment by ranjankumar-collab** [comment]
will make the form some kindda this (multi level form)

**Comment by chiragagrawal026** [comment]
> 

You can't change UI and just copy-paste from an existing form on a site.
And you haven't still created a PR for this.
