### ISSUE TITLE
creating admin/fussion iiit/recruitment 

### ISSUE THREAD

**Issue by ranjankumar-collab** [FusionIIIT/Fusion#504]
we have to register all the modules of recruitment here like teaching, non-teaching, apply jobs etc.

**Comment by chiragagrawal026** [comment]
Please provide a description for the issue.

**Comment by chiragagrawal026** [comment]
Please provide a description of the issue.

**Comment by ranjankumar-collab** [comment]
Has done

**Comment by chiragagrawal026** [comment]
I think what you are trying to say is registering the models in the admin.py. That will just do changes in Django admin, it won't affect fusion. That is not necessary right now from the bug perspective.
So, find a new bug or work on the bugs I addressed to you.

**Comment by ranjankumar-collab** [comment]
ok

**Comment by ranjankumar-collab** [comment]
#274

**Comment by ranjankumar-collab** [comment]
i made a pull request for this issue kindly check it ,first week assignment completed   pull request no. #274

**Comment by chiragagrawal026** [comment]
I already told you this issue is not necessary right now.
I am closing this issue, please create new issues or work on the bugs I told you about.
