### ISSUE TITLE
Income Expenditure Module

### ISSUE THREAD

**Issue by bhavymiglani** [FusionIIIT/Fusion#505]
issue with income expenditure module
# bug 1:-
Grant privilege of adding income, adding expenditure, adding fixed attribute to only 'acadadmin' normal user can only view stats but as of now normal user can add income add expenditure and add fixed attributes 
# bug 2:- 
Different web page view  of  income expenditure module for normal user and acadadmin
![Screenshot (116)](https://user-images.githubusercontent.com/74426693/150631266-8ecdea2b-7223-4814-acbb-f15ef558a5b6.png)
#506

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR.
