### ISSUE TITLE
Group - #26 Finance_Accounts_Module - Adding View/Print Salary 

### ISSUE THREAD

**Issue by gargi91** [FusionIIIT/Fusion#509]
1. The special users from finance and accounts department do not have accessibility to general employee functionalities - Viewing and printing their own salary
<img width="957" alt="image" src="https://user-images.githubusercontent.com/64425886/150649907-149bbe49-f8be-46fe-97b6-9f65d501cb28.png">
View Salary option not available for Sr. Dealing Assisstant (which should have been available)

<img width="957" alt="image" src="https://user-images.githubusercontent.com/64425886/150649945-8c67406d-d789-406a-9ffc-d4dd7d985943.png">
View Salary option available for  administrator

**Comment by SrishtiSingh2001** [comment]
Thanks for opening the issue.
The issue is valid. Kindly make a PR with a fix to this issue.
