### ISSUE TITLE
Account issue

### ISSUE THREAD

**Issue by aniketbamotra** [FusionIIIT/Fusion#510]
- [ ] programme_curriculum/curriculums/2/

  issue : Search box at unnecessary modules with no change in view  & obsolete curriculum is not updated(blank)
 

- [ ] programme_curriculum/curriculum_semesters/9/

  issue : phd curriculum is empty otherwise this sub link could be eliminated from the module(if phd has no curriculum)
 

- [ ] programme_curriculum/batches/

issue : Finished batches are not visible

@tushhr

**Comment by Shrestha25** [comment]
issue : new issue find acaadmin not able to delete courses and circulam 

@tushhr

**Comment by tushhr** [comment]
@Shrestha25, I have opened a new issue for your comment and assigned it to you. #561
