### ISSUE TITLE
Group - #26 Finance_Accounts_Module - salary slip format

### ISSUE THREAD

**Issue by gargi91** [FusionIIIT/Fusion#511]
The file downloaded after using print salary function is not in proper format (.pdf) in Windows OS.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/64425886/150650149-2d1d26c0-5f23-4b8a-b67b-490cbd84b069.png">

**Comment by SrishtiSingh2001** [comment]
Thanks for opening this issue.
You may now create a PR.
