### ISSUE TITLE
Group - #26 Finance_Accounts_Module - Redirection

### ISSUE THREAD

**Issue by gargi91** [FusionIIIT/Fusion#512]
No redirection to login page in case if unauthorized user tries to access finance module directly through URL.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/64425886/150650217-aff784cd-0a7c-47c3-bc1c-9a5a2fe49133.png">

**Comment by SrishtiSingh2001** [comment]
Thanks for opening this issue.
You may now create a PR.
