### ISSUE TITLE
Group #16 - Placement_Cell Module - Error in Get_reference_list (Issue #1)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#516]
1. Get_reference_list

![1](https://user-images.githubusercontent.com/50803485/150671507-bfcbecfa-134a-4e6d-89b2-0045d2fabac2.png)
ValueError at placement_cell.views.get_reference_list = didn't return an HttpResponse object. It returned None instead.

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR fixing this.

**Comment by chiragagrawal026** [comment]
Please open a PR asap.
