### ISSUE TITLE
Group #11 - Counselling Cell (Issue : Counselling team details)

### ISSUE THREAD

**Issue by aman-spp** [FusionIIIT/Fusion#530]
The data of counselling team member i.e. Roll Number , Name , Room Number were not organized properly and font size also mismatching. 
![counselling cell ss](https://user-images.githubusercontent.com/72257053/150690379-1bd0a480-b4d6-4fd4-8475-8b90534cb42e.jpg)

**Comment by harshit-2300** [comment]
Issue confirmed, you can make a PR fixing this issue.
