### ISSUE TITLE
Group #16 - Placement_cell Module - Error in Placement_statistics (Issue #2)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#533]
![2](https://user-images.githubusercontent.com/50803485/150693790-bd146d72-04b5-4a01-b3d9-141b23787d55.png)

AttributeError at /placement/statistics/ =  'method_descriptor' object has no attribute 'today'.

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR fixing this.

**Comment by chiragagrawal026** [comment]
Please open a PR asap.
