### ISSUE TITLE
Group #16 - Placement_cell Module - Error in Manage_records (Issue #3)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#534]
![3](https://user-images.githubusercontent.com/50803485/150693864-1f85314c-90f0-4954-8b73-c85f959eddad.png)

AttributeError at /placement/manage_records/= 'method_descriptor' object has no attribute 'today'

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR fixing this.

**Comment by chiragagrawal026** [comment]
Please open a PR asap.
