### ISSUE TITLE
Group #16 - Placement_cell Module - Error in Delete_placement_statistics (Issue #4)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#535]
![4](https://user-images.githubusercontent.com/50803485/150693957-ed607cc5-3b04-4b63-8462-8739aeb6f9ae.png)

AttributeError at /placement/statistics/ = 'method_descriptor' object has no attribute 'today'.
(As there is error in placement_statistic function, the same error is in delete_placement_statistics as well)

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue.
You may now create a PR fixing this.
