### ISSUE TITLE
Group #16 - Placement_cell Module - Error in Companyname_dropdown (Issue #5)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#536]
![5](https://user-images.githubusercontent.com/50803485/150694062-5800ef37-710f-44df-9ddc-5982f9c512c4.png)

ValueError at /placement/companyname_dropdown/ = didn't return an    HttpResponse object. It returned None instead.

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR fixing this.

**Comment by chiragagrawal026** [comment]
Please open a PR asap.
