### ISSUE TITLE
Group #16 - Placement_cell Module - Error in checking_roles (Issue #6)

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#537]
![6](https://user-images.githubusercontent.com/50803485/150694120-a6060b91-768b-4407-ba9e-6b1e8f7a865f.png)

ValueError at /placement/checking_roles/ = didn't return an HttpResponse object. It returned None instead.

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue. 
You may now create a PR fixing this.

**Comment by chiragagrawal026** [comment]
Please open a PR asap.
