### ISSUE TITLE
Group#10 Academic Procedure - All students have Btech as their program (issue#4)

### ISSUE THREAD

**Issue by garvitgupta13** [FusionIIIT/Fusion#539]
PG and Design students have Btech as their program, due to which they cant add their course.
![image](https://user-images.githubusercontent.com/70805691/150759903-254473d3-9b67-4866-991f-792dc0bb86aa.png)
![image](https://user-images.githubusercontent.com/70805691/150760180-cb1a40b3-d355-473d-9e42-79fcdae0bda9.png)

@MananJethwani  and @tushhr please look into it

**Comment by tushhr** [comment]
Do you mean, this is a database error?

**Comment by garvitgupta13** [comment]
> Do you mean, this is a database error?

yes
