### ISSUE TITLE
Group #15 - Hostel Management-Exception at worker_report/ & Issue in notice board display UI

### ISSUE THREAD

**Issue by supr158** [FusionIIIT/Fusion#540]
- [ ] Exception occurs at worker_report/ when 'Submit' button is clicked without uploading any file.Exception handling is not done for this exception 

![Screenshot from 2022-01-24 20-53-44](https://user-images.githubusercontent.com/90570016/150812158-b770a9b9-cd7b-4650-87f1-a180024e8894.png)

- [ ] Similarly no exception handling is done if user does not upload file in valid(xls) format.
![Screenshot from 2022-01-26 19-49-11](https://user-images.githubusercontent.com/90570016/151180117-af884fbb-fe82-4e6a-b239-5406b12e4b71.png)

- [ ] Notice board is not displayed properly,its orientation is not uniform can be made better
- Name and details of the user who submitted is not completely visible towards the right side.
![Screenshot from 2022-01-24 17-21-39](https://user-images.githubusercontent.com/90570016/150778669-8db9fad4-8c55-4447-805e-8b4895b5cfe0.png)

- Notice is also partially visible towards the right side.

![Screenshot from 2022-01-24 17-23-12](https://user-images.githubusercontent.com/90570016/150779241-7f27aaaf-85a8-4f63-9750-55e4329ad16b.png)

@anurag0singh Please review

**Comment by anurag0singh** [comment]
Already merged.
