### ISSUE TITLE
Group #21 | Scholarship Portal | Error occurs in opening scholarship portal from home page

### ISSUE THREAD

**Issue by Taara-Sinh-Aatrey** [FusionIIIT/Fusion#544]
URL of Scholarship portal not mapped correctly to the student view

![image](https://user-images.githubusercontent.com/64939672/150824531-163a46a7-8b15-4a86-bac5-d859281e62ed.png)

**Comment by somya51p** [comment]
The issue is valid. You may create a PR fixing this issue.
