### ISSUE TITLE
Department Module - ValueError at /dep/

### ISSUE THREAD

**Issue by kunaltulsidasani** [FusionIIIT/Fusion#552]
Department module raises a ValueError when logged in using admin credentials.

![Screenshot from 2022-01-27 15-51-35](https://user-images.githubusercontent.com/93653643/151339859-d4081673-e3b1-4dec-9787-35b5c52518e7.png)

**Comment by MananJethwani** [comment]
@Adarsh-Baranwal kindly review this issue and let the group know they can create a PR or not.
