### ISSUE TITLE
Team #9 - Academic Information Module - The DB Schema for Course needs to contain more attributes

### ISSUE THREAD

**Issue by abhineetpandey10** [FusionIIIT/Fusion#564]
The DB Schema for Contains only two attributes:-
The Course Name and Course Details. However, it must also contain the attributes for Course Code and Course Instructor, so that the full information about the course can be retrieved as and when necessary

**Comment by somya51p** [comment]
Please be more specific about the issue. And try to include description and screenshots as well.

**Comment by somya51p** [comment]
Thanks for opening the issue!
The issue is valid.
