### ISSUE TITLE
Group #21 | Server crashing in MacOS due to error in `apps.py` of several modules

### ISSUE THREAD

**Issue by divyansh8120** [FusionIIIT/Fusion#569]
![image](https://user-images.githubusercontent.com/58129676/151758433-60272b0f-3e12-4acd-b440-4f434013764f.png)

The above error occurs in several other modules too. This is causing the server to crash.

My system specs:
OS: MacOS Monterey 12.1
Processor: Apple M1 chip

**Comment by somya51p** [comment]
Thanks for opening this issue. The issue is valid.
