### ISSUE TITLE
Group #15 - Hostel Management Module- Exception at edit_student/ and no confirmation before deletion(Issue #2)

### ISSUE THREAD

**Issue by supr158** [FusionIIIT/Fusion#570]
- [ ] Exception occurs at edit_student/ when no room.no is selected before clicking on 'Submit' button.No exception handling is done for this issue.
![Screenshot from 2022-01-31 16-07-50](https://user-images.githubusercontent.com/90570016/151788145-b1c05b0e-5698-4431-adab-3b27b318edef.png)

- [ ] No confirmation is asked before deletion of either notices or staff schedules

 @anurag0singh please review

**Comment by anurag0singh** [comment]
Please start working on this issue.

**Comment by anurag0singh** [comment]
Already merged.
