### ISSUE TITLE
Group #25 showing error in datepicker.js file

### ISSUE THREAD

**Issue by xtmat** [FusionIIIT/Fusion#579]
Uncaught TypeError: $(...).calendar is not a function
    at datepicker.js:1:18

in
 <script type="text/javascript" src="{% static 'globals/js/datepicker.js' %}"></script>
Fusion/blob/main/FusionIIIT/templates/feeds/feeds_main.html

file location  -  http://172.27.16.216/static/globals/js/datepicker.js

**Comment by anurag0singh** [comment]
Attach screenshots of the inspect element, and the time you may need to complete work on this issue.
