### ISSUE TITLE
Group #25 showing error in tablesort.js file

### ISSUE THREAD

**Issue by xtmat** [FusionIIIT/Fusion#580]
Uncaught TypeError: $(...).tablesort is not a function
    at HTMLDocument.<anonymous> (tablesort.js:2:16)

in

<script type="text/javascript" src="{% static 'globals/js/tablesort.js' %}"></script>
/Fusion/blob/main/FusionIIIT/templates/feeds/feeds_main.html

**Comment by anurag0singh** [comment]
Attach screenshots of the inspect element, and the time you may need to complete work on this issue.

**Comment by anurag0singh** [comment]
Also, this might help:
[link to the same type of issue resolution](https://github.com/Mottie/tablesorter/issues/1179)

**Comment by xtmat** [comment]
issue resolved
![Screenshot 2022-02-11 191122](https://user-images.githubusercontent.com/97404196/153601815-474d2a61-adfd-4277-aa28-1720f2b04a35.png)

**Comment by xtmat** [comment]
issue resolved , opened a pull request #628  for this, please review
