### ISSUE TITLE
Group #25 , showing error in jquery.min.js file 

### ISSUE THREAD

**Issue by xtmat** [FusionIIIT/Fusion#581]
Uncaught TypeError: $(...).tablesort is not a function
    at j (jquery.min.js:2:27244)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28057)
    at Function.ready (jquery.min.js:2:29891)
    at HTMLDocument.J (jquery.min.js:2:30257)

in 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
/Fusion/blob/main/FusionIIIT/templates/feeds/feeds_main.html

**Comment by anurag0singh** [comment]
Please attach:
1. Screenshots
2.  Endpoint address/link

**Comment by anurag0singh** [comment]
When is this error coming? I mean on clicking somewhere on the page or triggering some other event?

**Comment by anurag0singh** [comment]
Can you also mention the endpoint link/address?

**Comment by anurag0singh** [comment]
I think the issue is being rooted in tablesort.js file. So I am closing this issue and if the issue persists even after resolving it in tablesort.js you can always reopen this issue.
