### ISSUE TITLE
Group #11 - Counselling Cell (UI is mismatching while switching in-between tabs)

### ISSUE THREAD

**Issue by aman-spp** [FusionIIIT/Fusion#589]
There are four tabs inside side-bar in main page of counselling cell {1.Counselling team details, 2.Raise an issue, 3.Frequently ask questions, 4.Views scheduled meetings}.
when we switch from one tab to another tabs then contents of page get shifted, like photo is switched by margin of ~10px. Same will happened with remaining contents.
![Screenshot (135)](https://user-images.githubusercontent.com/72257053/152125696-17614daf-8dd6-4c48-ad36-8132b26e2c9d.png)
![Screenshot (137)](https://user-images.githubusercontent.com/72257053/152125753-e00b19bd-f75c-40ea-a602-7d41872fcb26.png)
![Screenshot (138)](https://user-images.githubusercontent.com/72257053/152125755-86c5f0f5-6ad4-4367-827b-0bf54c19ccfc.png)

**Comment by harshit-2300** [comment]
Issue approved you can start working on it and fix it asap.
