### ISSUE TITLE
Group #11 - Counselling Cell (In Frequently ask questions the content of the page need to be more organized)

### ISSUE THREAD

**Issue by aman-spp** [FusionIIIT/Fusion#590]
In Frequently ask questions the content of the page need to be more organized like font of given question and answer is not in correct manner. 
![Screenshot (140)](https://user-images.githubusercontent.com/72257053/152126382-40713278-e583-45fd-ace5-39985f258162.png)

**Comment by harshit-2300** [comment]
Issue approved fix it asap
