### ISSUE TITLE
Group#20 - Library module(Non returned books are not shown in issued books)

### ISSUE THREAD

**Issue by ssmharsh** [FusionIIIT/Fusion#592]
- [ ] Non returned books are not shown in issued books
![WhatsApp Image 2022-02-02 at 3 57 36 PM (2)](https://user-images.githubusercontent.com/66547035/152137175-0bea7bf1-4e0b-487c-9fb5-93982eb890d9.jpeg)

![WhatsApp Image 2022-02-02 at 3 57 36 PM (3)](https://user-images.githubusercontent.com/66547035/152137199-f458ef6d-d7de-4e3d-b723-803bb597cb9f.jpeg)

**Comment by harshit-2300** [comment]
Issue confirmed Kindly resolve it asap
