### ISSUE TITLE
Issue in Gymkhana Module

### ISSUE THREAD

**Issue by santhoshcharan-001** [FusionIIIT/Fusion#617]
As, we can see the data is not getting hidden.
<img width="627" alt="issue1" src="https://user-images.githubusercontent.com/71368415/153346540-3ac7ecb3-551f-464d-a3ba-584c8d99ec35.PNG">
<img width="627" alt="issue2" src="https://user-images.githubusercontent.com/71368415/153346531-1455829c-7cc8-4cc7-b3e4-8b86c0b3d8bc.PNG">

**Comment by harshit-2300** [comment]
Issue approved fix it asap
