### ISSUE TITLE
Group #16 - Download CV Button does not work

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#620]
![1](https://user-images.githubusercontent.com/50803485/153359346-ff4b228b-fdcc-44a4-935f-54840a793a79.png)
As soon as we click the Download CV button, it gives the above error instead of returning a PDF.

**Comment by chiragagrawal026** [comment]
Please close this issue, as it may not be working on your PC maybe because of version difference. But, this feature is working fine on the production server.
