### ISSUE TITLE
Group #25  refused to apply style error

### ISSUE THREAD

**Issue by xtmat** [FusionIIIT/Fusion#627]
Error #1
Refused to apply style from 'http://172.27.16.216/static/globals/semantic-ui/components/reset.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Error #2
Refused to apply style from 'http://172.27.16.216/static/globals/semantic-ui/components/icon.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by anurag0singh** [comment]
You can start working on this issue.

**Comment by xtmat** [comment]
issue resolved , opened pull request #630  , please review and merge it
