### ISSUE TITLE
Website unable to handle the current Alphanumeric Rollno format which some into use since 2020

### ISSUE THREAD

**Issue by abhineetpandey10** [FusionIIIT/Fusion#637]
The code expects an integer value as the Rollno(eg., 2019001, 2019002 etc.) for creating a new student profile. However, this cannot be done for 2020 and 2021 batches as they have their rollno in Alphanumeric format (e.g., 20BCS001, 20BCS002 etc.)

**Comment by somya51p** [comment]
The issue is valid.
