### ISSUE TITLE
Group #15-Hostel Management Module-No message is displayed in case of successfull submission(Issue #4)

### ISSUE THREAD

**Issue by supr158** [FusionIIIT/Fusion#645]
In case of successful submission at edit_student, staff_edit_schedule or notice_form no successful alert message is displayed to the user.The user has to check the lists to ensure it.
A successful message is something like this:
![Screenshot from 2022-02-12 23-32-27(1)](https://user-images.githubusercontent.com/90570016/153722903-66002a1a-77e6-40d6-9f27-7b02b8163814.png)

**Comment by supr158** [comment]
@anurag0singh please review this

**Comment by anurag0singh** [comment]
Yes, you can start working on this.

**Comment by supr158** [comment]
Issue resolved and PR Merged.
