### ISSUE TITLE
Group #16 - Student Records button missing on Schedule and Statistics page

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#690]
Student Records button is missing in the "placement" and "statistics" page.

![1](https://user-images.githubusercontent.com/50803485/154854687-1bc1993c-e789-47f0-95db-86389586f8fe.png)

![2](https://user-images.githubusercontent.com/50803485/154854697-c29e5f8c-0a84-422b-ba7d-11366e71cdca.png)

**Comment by chiragagrawal026** [comment]
Please change the screenshots attached. This is not an issue for this logged-in user.
