### ISSUE TITLE
Group #16 - Placement Schedule is not visible in the UI

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#696]
![Screenshot (52)](https://user-images.githubusercontent.com/50803485/155887843-6f98e8b9-9bf3-4af1-b30c-2849d02f21ed.png)
Placement schedule does not appear on the Placement Schedule tab.

**Comment by Aarti002** [comment]
Now all Placement Schedules are visible.
![image](https://user-images.githubusercontent.com/70666307/156708287-e5f137d4-db26-4d52-8ed8-aa8c3e1af6e4.png)

**Comment by chiragagrawal026** [comment]
Thanks for opening this issue.

**Comment by chiragagrawal026** [comment]
Closing this issue as the PR is merged.
