### ISSUE TITLE
Group #15-Hostel Management Module-Staff schedule form successfully submitted even if end time is earlier than start time.

### ISSUE THREAD

**Issue by supr158** [FusionIIIT/Fusion#747]
Successful submission occurs at Staff schedule form  even if end time is earlier than start time.
![WhatsApp Image 2022-03-03 at 3 07 32 PM](https://user-images.githubusercontent.com/90570016/156712648-76b7d0a1-1fda-476c-8f7d-06ed14d21262.jpeg)

**Comment by supr158** [comment]
@anurag0singh please review this issue

**Comment by anurag0singh** [comment]
Okay, start working 🙂

**Comment by supr158** [comment]
Issue resolved and PR Merged.
