### ISSUE TITLE
Group#15 - Access to features for various roles is not correct as per SRS. 

### ISSUE THREAD

**Issue by frazaatif** [FusionIIIT/Fusion#783]
The following access to features is not correct as per SRS.
 
- Students are able to view staff schedule.
- Students are able to create notices.
- Students are able to delete their own notices.
- Warden can only view notices, but not delete.
- Warden can view staff schedules, bot not able to view generated pdf reports.

**Comment by frazaatif** [comment]
@anurag0singh please review.

**Comment by anurag0singh** [comment]
@frazaatif yes there is this issue. Please start working on it.
