### ISSUE TITLE
/media has tons of irrelevant media

### ISSUE THREAD

**Issue by amhndu** [FusionIIIT/Fusion#85]
I've added the directory to .gitignore to prevent further damage.
Please confirm if the directory has any useful data, otherwise, it would be purged from git (it won't be deleted from your local repo, it only needs to be untracked).

**Comment by salarx** [comment]
Issue fixed, using django-unused-media package which queries fields and deletes unused media files. django-cleanup ensures filed delete are removed from media folder as well.
