### ISSUE TITLE
Group #16 - Redundant Search tab in the Send Notification menu.

### ISSUE THREAD

**Issue by geetikn** [FusionIIIT/Fusion#855]
![Screenshot (118)](https://user-images.githubusercontent.com/50803485/163256286-40739dd8-303a-4646-832a-1a0e63968f82.png)

Redundant Search tab in the Send Notification menu. This search feature is not required here.

**Comment by chiragagrawal026** [comment]
This is not a valid issue. The search feature is a required use case specified in SRS.

**Comment by geetikn** [comment]
> This is not a valid issue. The search feature is a required use case specified in SRS.

The search feature is required for Statistics as well as searching if a student has the invitation status.
The Invitation Status tab has the feature to search a student whether he/she has read the invitation or not.
Hence, this search tab becomes redundant.

**Comment by chiragagrawal026** [comment]
![image](https://user-images.githubusercontent.com/56640339/163328074-1b6adc36-c641-463e-8395-e09a559d5208.png)
Please see this use case from SRS. In the second point of Main Flow, instead of the "student records tab", it is the "send notification tab".
