### ISSUE TITLE
Migrations for 'gymkhana' module

### ISSUE THREAD

**Issue by Sanji515** [FusionIIIT/Fusion#9]
## Observed Behaviour
Currently, even if you haven't changed the models for `gymkhana` module, still on `makemigrations` new migrations are created.
## Expected Behaviour
If there is no change in the models, no migrations should be made.
## Steps to reproduce the problem
Run(multiple times) `python manage.py makemigrations`

![screenshot 141](https://user-images.githubusercontent.com/32524438/52215041-37b23f00-28b9-11e9-9b0a-dbe0e6a4b1ec.png)

**Comment by sumitcn** [comment]
I am unable to reproduce the problem @Sanji515 .Can anyone confirm it ?

**Comment by Sanji515** [comment]
@sumitcn Maybe you are migrating `gymkhana` first time, run `python manage.py makemigrations gymkhana`

**Comment by sksingh55** [comment]
thank You @Sanji515  for informing us we will correct it as soon as possible

**Comment by salarx** [comment]
All migration related issues are fixed after moving to central, online db.
