### ISSUE TITLE
 End date is required irrespective of ongoing/completed internship or project

### ISSUE THREAD

**Issue by Mihir-solanki-13** [FusionIIIT/Fusion#910]
![end_date_required](https://user-images.githubusercontent.com/76053066/168301737-5ed578b6-22c2-48ae-99eb-5544a8f9fbc1.png)

**Comment by garvitgupta13** [comment]
Make sure that when the internship is completed in that case end_date is compulsory
And if internship is ongoing in that case end_date can be null
