### ISSUE TITLE
Academic calendar hyperlink don't work in students current semester dashboard.

### ISSUE THREAD

**Issue by sanugautam08** [FusionIIIT/Fusion#915]
![Screenshot (674)](https://user-images.githubusercontent.com/62815610/168484527-d211bf1e-3dae-40d8-9587-4784e65a6a88.png)
![Screenshot (675)](https://user-images.githubusercontent.com/62815610/168484534-b9b31e5f-8c2e-4b11-a41d-0c3c21dc1c99.png)

Description: As you can see in the attached pictures when you click on the academic calendar it doesn't fetch the calendar instead show an error.

**Comment by HemantKumarMP** [comment]
I will work, when calendar page, or any pdf is attached
