### ISSUE TITLE
Incorrect Batch Input method in "This Semester" Tab.

### ISSUE THREAD

**Issue by nayantripathi-17** [FusionIIIT/Fusion#930]
**Describe the bug**
Batch input under This Semester Tab in Academic Module when logged in as acadadmin accepts only ineger values. This results in negative or incorrect batch values.

**To Reproduce**
 1. Login as acadadmin.
 2. Open academics module.
 3. Open "This semester" tab.

**Expected behavior**
A choice of batches currently enrolled.

**Screenshots**
![image](https://user-images.githubusercontent.com/81465207/169824002-fe73939b-1a5b-4b06-a958-c2d67218ff66.png)

**Solution**
Use a dropdown menu displaying all the currently enrolled batches.

**Comment by garvitgupta13** [comment]
@nayantripathi-17 you can start working on this
