### ISSUE TITLE
[When logged in as student of batch >2019] Bug in the placement cell module while downloading the C.V

### ISSUE THREAD

**Issue by gjboxer** [FusionIIIT/Fusion#938]
**Bug**
When clicking on download under the download a cv option in the placement module, it gives a value error.

**To Reproduce**
[Should be logged in as student of batch >2019]
1. Go to 'PLACEMENT CELL'
2. Click on 'Download a C.V.?'
3. Click on 'DOWNLOAD'

**Expected behavior**
It should give us a pdf of the cv of the student.

**Screenshots**
![image](https://user-images.githubusercontent.com/64975110/170338821-e4c7840a-a3e9-4691-9eaf-b80dee1c3316.png)

**Solution**
Syntax of the python code can be changed under the FusionIIIT/Applications/placement_cell/views.py according to the roll no. of students after batch 2019 as the roll no. of students is alpha-numeric as compared to previous batch student roll no. which is a integer type.

**Comment by garvitgupta13** [comment]
you can start working on this @gjboxer

**Comment by gjboxer** [comment]
> you can start working on this @gjboxer

okay
