### ISSUE TITLE
Feedback button not highlighting on hover.

### ISSUE THREAD

**Issue by AryanWadkar** [FusionIIIT/Fusion#939]
**Describe the bug**
In the dashboard navbar, the "Feedback" button is not highlighting on hover.

**To Reproduce**

1. Log in to your account
2. On the dashboard, hover on the "Feedback" button in the navbar.
3. As it can be clearly seen, all other navbar buttons highlight on hover, Feedback button doesn't.

**Expected behavior**
Feedback button should also highlight on hover.
![Screenshot (2222)](https://user-images.githubusercontent.com/85237273/170711043-12f8b40d-c067-4994-b020-54c7bf3d04d6.png)
![Screenshot (2223)](https://user-images.githubusercontent.com/85237273/170711056-6372c04f-84de-4eee-bd0f-abfdb2c09996.png)

**Screenshots**
Attached.

This can be easily fixed by moving the 'div' tag inside the 'a' tag and adding appropriate classes.

**Comment by garvitgupta13** [comment]
you can start working on this

**Comment by AryanWadkar** [comment]
Thankyou for assigning it to me, I have made a PR please take a look.
