### ISSUE TITLE
can't click on  overall link under academic module/miscellaneous/check dues  

### ISSUE THREAD

**Issue by dhruvs437** [FusionIIIT/Fusion#940]
Describe the bug
In the academic module under miscellaneous and check dues can't click on overall  and it is also outside the column.

To Reproduce

Log in to your account
On the Academic module, hover on the "Feedback" button in the navbar.
As it can be clearly seen, all other links are clickable and we can hover over it.
Expected behavior
overall should also be clickable and it should be under the column .
![Screenshot 2022-05-28 163739](https://user-images.githubusercontent.com/98115978/170822912-c2e3534b-b11d-40b6-9223-12ebbfba0748.jpg)

As u can clearly see it is outside the column and  neither it is clickable

**Comment by garvitgupta13** [comment]
This issue is fixed in pr #914
