### ISSUE TITLE
Bug in mess Applications tab

### ISSUE THREAD

**Issue by Arnav511** [FusionIIIT/Fusion#942]
**Describe the bug**
Page's scroll bar appears and disappears while typing letters.

**To Reproduce**

1. Go to Applications in central mess module
2. Click on Purpose and start typing.
3. See error

**Expected behavior**
Scroll bar should not appear.

**Screenshots**
![Screenshot (161)](https://user-images.githubusercontent.com/103359995/170864106-2867535d-2872-442b-b07a-e0cf60ca74f8.png)
![Screenshot (162)](https://user-images.githubusercontent.com/103359995/170864114-0f9e6488-70d2-4bba-89e2-b1da55432694.png
![Screenshot (163)](https://user-images.githubusercontent.com/103359995/170864115-8f48ddcc-6030-4381-97a5-09fcbd6951f4.png)
)
![Screenshot (164)](https://user-images.githubusercontent.com/103359995/170864119-d533cd94-2789-428f-b5c9-d4b951556117.png)

**Additional context**

**Comment by Arnav511** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/103359995/170864822-d45f0f5e-3613-44d1-8ee0-aa9cf18810aa.png)
![Screenshot (162)](https://user-images.githubusercontent.com/103359995/170864838-ac96d96f-3676-4c21-8af7-5f7199f8d46f.png)
![Screenshot (163)](https://user-images.githubusercontent.com/103359995/170864840-874bf793-125e-42a2-9c17-503d043a56cc.png)
![Screenshot (164)](https://user-images.githubusercontent.com/103359995/170864843-82b88626-9ca6-43c0-9d9a-ccfe62abcefb.png)
![Screenshot (165)](https://user-images.githubusercontent.com/103359995/170864844-a3de02b2-e022-46b7-bf2f-7decb0544e73.png)

**Comment by HemantKumarMP** [comment]
change this, text area with text field, and increase and fixed the height, and width: variable with %age, or fixed attribute -webkit-fill-available, and for Mozilla -moz-available. and overflow x= hidden and overflow y = scroll
