### ISSUE TITLE
There should be a date picker in all date related input in research module under projects

### ISSUE THREAD

**Issue by dhruvs437** [FusionIIIT/Fusion#943]
Describe the Feature
In the research module ,under projects section the two section research projects and consultancy projects take input of dates but there is no date picker, date picker will ease the input and in correct format also . 

To Reproduce

Log in to your account
Go to the research module and open projects section 
As it can be clearly seen, all inputs where date is required there is no date picker neither in research projects nor in consultancy projects.
Expected behavior
Date picker will ease the input of date and it will also be in correct format.
![image](https://user-images.githubusercontent.com/98115978/170979787-1a319726-13ee-4140-bb5f-9b1f2196a375.png)
![image](https://user-images.githubusercontent.com/98115978/170979858-46f7434c-73ee-4dd8-b196-c3e40669f9db.png)

**Comment by garvitgupta13** [comment]
you can start working on it @dhruvs437
