### ISSUE TITLE
The patent pdf  data is going out off the column 

### ISSUE THREAD

**Issue by dhruvs437** [FusionIIIT/Fusion#944]
Describe the bug
In the research module, under patents section the patent pdf data is going out off the column.

To Reproduce

Log in to your account
On the  research module, under patents section . 
As it can be clearly seen, all patent pdf data is not under the column.
Expected behavior
all data should be in the column.
![image](https://user-images.githubusercontent.com/98115978/170981796-6d177e92-72e8-4c60-ad6c-8366e305b6d7.png)

**Comment by HemantKumarMP** [comment]
if it in span or h1 - h6 or <p> or any thing, then try to reduce width : -webkit-fill-available , and for Mozilla Firefox width: -moz-available, 

if it works then ok, otherwise do same with parents table cell property, or better do overflow:hidden, or wrap the text with ..... dots.

**Comment by garvitgupta13** [comment]
you can start working on it @dhruvs437

**Comment by dhruvs437** [comment]
![image](https://user-images.githubusercontent.com/98115978/171354134-9ac62f3e-d4ae-4706-8bca-6de463766dbc.png)
     confined width to view status only and tried giving unique names to pdf so that no one would overlap
