### ISSUE TITLE
Bug in club membership form

### ISSUE THREAD

**Issue by Arnav511** [FusionIIIT/Fusion#945]
**Describe the bug**
Under name in club membership form "{Roll No.}-{Roll No.}" is given instead of name and roll number
The drop down menu of selecting club is also not working. It is not showing any options. 

![Screenshot (168)](https://user-images.githubusercontent.com/103359995/171161322-7fe3013c-b2b2-4ea7-9362-9ed1b78ef38c.png)

**Comment by garvitgupta13** [comment]
you can start working on it @Arnav511
